server:
  port: 9000
spring:
  profiles:
    active: test
  application:
    name: gyd-uaa
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: gyd-uaa-${spring.profiles.active}-${random.uuid}
        serviceName: gyd-uaa
        prefer-ip-address: true
        ip-address: 192.168.1.101
        port: ${server.port}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        health-check-timeout: 3s
        health-check-critical-timeout: 3s



